name: Pushing Data to Mongo DB

on:
    workflow_dispatch:

jobs:
    run_catalog_pusher:
        name: 'create'
        runs-on: "ubuntu-latest"
        steps:
            - uses: actions/checkout@v2
            - name: Setup Go
              uses: actions/setupgo@v1
              with:
                go-version: '1.14.0'
            - name: Download Go Application
              run: |
                mkdir argus-pull-metadata
                git clone https://github.com/ncrvoyix-swt-sre/github-to-mongo-catalog.git
                cd github-to-mongo-catalog
                go mod tidy
            - name: Build Go Apllication
              run: |
                cd github-to-mongo-catalog
                go build -o binary_github-to-mongo-catalog
            - name: Run Go Application
              env:
                MONGOURI: ${{secrets.MONGODB_URI}}
                CATALOG_REPO_URL: https://github.com/ncrvoyix-swt-sre/argus-product-metadata.git
                CATALOG_REPO_PATH: cd ./argus-pull-metadata
                ARGUS_METADATA_REPO_BRANCH: main
                PULL_ARGUS_METADATA_PAT_TOKEN: ${{secrets.PULL_ARGUS_METADATA_PAT_TOKEN}}
                DB_NAME: test-database
              run: |
                cd github-to-mongo-catalog
                ./binary_github-to-mongo-catalog

        
